### ISSUE TITLE
Convert datetimes to UTC

### ISSUE THREAD

**Issue by madleech** [mattbeedle/capsule_crm#92]
All datetimes sent to Capsule have Z on the end indicating UTC/Zulu time, however no conversion is done on supplied dates before stftiming them.

```ruby
> date = DateTime.new(2015, 02, 26, 10, 30, 00, '+1300')
=> Thu, 26 Feb 2015 10:30:00 +1300

> date.strftime('%Y-%m-%dT%H:%M:%SZ')
=> "2015-02-26T10:30:00Z" # still in local timezone != UTC

> date.utc.strftime('%Y-%m-%dT%H:%M:%SZ')
=> "2015-02-25T21:30:00Z"
```

Is it possible to get this fixed?

**Comment by mattbeedle** [comment]
Good catch @madleech. I'll look into this as soon as I have the chance.
